name: dogma_polymer
author: Don Olmstead <don.j.olmstead@gmail.com>
homepage: http://dogma-dart.github.io/
version: 0.0.1
environment:
  sdk: '>=1.12.0 <2.0.0'
description: Polymer components for the Dogma libraries
dependencies:
  polymer: '1.0.0-rc.6'
  reflectable: 0.3.3
  web_components: ^0.12.0
  dogma_mapper: '^0.0.1'
  dogma_connection: '^0.0.1'
  dogma_rest_connection: '^0.0.1'
  dogma_rest_client: '^0.0.1'
  dogma_convert: '^0.0.1'
dev_dependencies:
  test: '^0.12.5+1'
transformers:
- web_components:
    enty_points:
    - test/model_element_test.html
- reflectable:
    entry_points:
    - test/model_element_test.dart
- $dart2js:
    $include: '**/*.bootstrap.initialize.dart'
